package testvh.yz.com.SQL;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import testvh.yz.com.SQL.MESSAGE;
import testvh.yz.com.SQL.Person;
import testvh.yz.com.SQL.Student;
import testvh.yz.com.SQL.Teacher;

import testvh.yz.com.SQL.MESSAGEDao;
import testvh.yz.com.SQL.PersonDao;
import testvh.yz.com.SQL.StudentDao;
import testvh.yz.com.SQL.TeacherDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mESSAGEDaoConfig;
    private final DaoConfig personDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig teacherDaoConfig;

    private final MESSAGEDao mESSAGEDao;
    private final PersonDao personDao;
    private final StudentDao studentDao;
    private final TeacherDao teacherDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mESSAGEDaoConfig = daoConfigMap.get(MESSAGEDao.class).clone();
        mESSAGEDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        teacherDaoConfig = daoConfigMap.get(TeacherDao.class).clone();
        teacherDaoConfig.initIdentityScope(type);

        mESSAGEDao = new MESSAGEDao(mESSAGEDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        teacherDao = new TeacherDao(teacherDaoConfig, this);

        registerDao(MESSAGE.class, mESSAGEDao);
        registerDao(Person.class, personDao);
        registerDao(Student.class, studentDao);
        registerDao(Teacher.class, teacherDao);
    }
    
    public void clear() {
        mESSAGEDaoConfig.clearIdentityScope();
        personDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
        teacherDaoConfig.clearIdentityScope();
    }

    public MESSAGEDao getMESSAGEDao() {
        return mESSAGEDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public TeacherDao getTeacherDao() {
        return teacherDao;
    }

}
