package testvh.yz.com.SQL;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MESSAGE".
*/
public class MESSAGEDao extends AbstractDao<MESSAGE, Long> {

    public static final String TABLENAME = "MESSAGE";

    /**
     * Properties of entity MESSAGE.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SendMessageuid = new Property(1, String.class, "SendMessageuid", false, "SENDMESSAGEUID");
        public final static Property ReviceMessageuid = new Property(2, String.class, "reviceMessageuid", false, "REVICEMESSAGEUID");
        public final static Property Msg = new Property(3, String.class, "msg", false, "MSG");
        public final static Property Post = new Property(4, String.class, "post", false, "POST");
    }


    public MESSAGEDao(DaoConfig config) {
        super(config);
    }
    
    public MESSAGEDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MESSAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"SENDMESSAGEUID\" TEXT," + // 1: SendMessageuid
                "\"REVICEMESSAGEUID\" TEXT," + // 2: reviceMessageuid
                "\"MSG\" TEXT," + // 3: msg
                "\"POST\" TEXT);"); // 4: post
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MESSAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MESSAGE entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String SendMessageuid = entity.getSendMessageuid();
        if (SendMessageuid != null) {
            stmt.bindString(2, SendMessageuid);
        }
 
        String reviceMessageuid = entity.getReviceMessageuid();
        if (reviceMessageuid != null) {
            stmt.bindString(3, reviceMessageuid);
        }
 
        String msg = entity.getMsg();
        if (msg != null) {
            stmt.bindString(4, msg);
        }
 
        String post = entity.getPost();
        if (post != null) {
            stmt.bindString(5, post);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MESSAGE entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String SendMessageuid = entity.getSendMessageuid();
        if (SendMessageuid != null) {
            stmt.bindString(2, SendMessageuid);
        }
 
        String reviceMessageuid = entity.getReviceMessageuid();
        if (reviceMessageuid != null) {
            stmt.bindString(3, reviceMessageuid);
        }
 
        String msg = entity.getMsg();
        if (msg != null) {
            stmt.bindString(4, msg);
        }
 
        String post = entity.getPost();
        if (post != null) {
            stmt.bindString(5, post);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MESSAGE readEntity(Cursor cursor, int offset) {
        MESSAGE entity = new MESSAGE( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // SendMessageuid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // reviceMessageuid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // msg
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // post
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MESSAGE entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSendMessageuid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setReviceMessageuid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMsg(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPost(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MESSAGE entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MESSAGE entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MESSAGE entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
